include:
#  - local: pipelines/.test_energy_measurement.yaml
  - local: pipelines/.energy_measurement.yaml

# Define environment variables
variables:
  LABPC_IP: "192.168.170.23" # IP address of the LABPC
  PM_IP: "192.168.170.22" # IP address of the PM (Power Meter)

stages:
#  - test-build
#  - test-energy_measurement
#  - test-result
  - build
  - energy_measurement
  - result
