<!--
# ======================================= #
# The beginning of the script is specific #
# for Idle Mode or SUS scenario.          #
# ======================================= #
-->

---
header-includes:
- \usepackage{comment}
- \usepackage{url}
lang: en-US
output:
  pdf_document:
     keep_tex: true
     number_sections: TRUE
  highlight: tango
  fig_caption: yes
  toc: yes
params:
  title: ''
  baselineStartmarkers: !r data.frame(0)
  baselineEndmarkers: !r data.frame(0)
  startActions: !r data.frame(0)
  stopActions: !r data.frame(0)
  startmarkers: !r data.frame(0)
  endmarkers: !r data.frame(0)
  measurementCount: -1
  shortestTestrun: 0
  longestTestrun: 0
  measurementName: '---'
  SUT: 'Standard Usage Scenario'
  performanceBaseline: !r data.frame(0)
  performanceMeasurement: !r data.frame(0)
  performanceMeasurementActions: !r data.frame(0)
  allPerformanceMeasurements: !r data.frame(0)
  allPerformanceBaselines: !r data.frame(0)
  powerBaseline: !r data.frame(0)
  powerMeasurement: !r data.frame(0)
  powerMeasurementActions: !r data.frame(0)
  allPowerMeasurements: !r data.frame(0)
  allPowerBaselines: !r data.frame(0)
  evaluateGpuMeasurement: FALSE
  gpuBaseline: !r data.frame(0)
  gpuMeasurement: !r data.frame(0)
  gpuMeasurementActions: !r data.frame(0)
  allGpuMeasurements: !r data.frame(0)
  allGpuBaselines: !r data.frame(0)
  watthours: 0
  baselineWatthours: 0
  modelHistory: NULL
  allEpochsMeans: !r data.frame(0)
  historyMeans: !r data.frame(0)
  subtitle: ''
  baselineCount: -1
  whatToPlot: !r list()
  actionNames: !r c("a","b")
  graphicsFolder: "sus_graphics"
---

---
title: "`r params$title`"
subtitle: "`r params$subtitle`"
documentclass: article
---

```{r child = 'anaylsis_script_Report.Rmd'}
```
